# General Settings
deterministic: true
sampler_seed: 99
seed: 99
one_seeded: true  # Set to true to use same seed for data and model

# Dataset Configuration
dataset: "cifar100"
data_dir: null  # Set to null for default paths
batch_size: [256, 512]  # Added 256 batch size option
num_workers: 4

# Model Configuration
model: ["resnet9" ]
optimizer: "adamw"
# Training Parameters
epochs: 150
lr: [1.e-2, 7.e-3]  # Good range for CIFAR-100
weight_decay: [0.005]  # Added lower value for CIFAR-100
beta1: 0.9  # Fixed to standard value 
beta2: 0.99
eps: 1.e-8
do_bias_correction: [false, true]  # Your experimental variable

# Scheduler Configuration  
scheduler: "warmup_cosine"
warmup_steps: 0.05
lr_start: 1.e-6
lr_end: 1.e-6
cooldown_steps: null

# Logging Configuration
use_wandb: true
wandb_project: "bias_correction_experiments"
wandb_dir: "./wandb_logs"
wandb_api_key: ""
out_dir: "/fast/slaing/exp/vision"

# Checkpoint Configuration
save_intermediate_checkpoints: false
save_last_checkpoint: true
resume: false
resume_exp_name: null
over_write: false