# General Settings
deterministic: true
sampler_seed: null 
seed: [55, 56, 57, 58]
one_seeded: true  # Set to true to use same seed for data and model

# Dataset Configuration
dataset: "cifar100"
data_dir: null  # Set to null for default paths
batch_size: 256  # Added 256 batch size option
num_workers: 4
cutmix: 0 #the alpha for the beta distribution lambda is drawn from 
cutmix_probability: 0
val_size: 0.2
#dropout: 0.05
# Model Configuration
pretrained: false
model: ["resnet56" ]
optimizer: "adamw"
# Training Parameters
epochs: 175
lr: [0.0003, 0.001, 0.003] 
weight_decay: [0.0075]  
beta1: [0.9]  
beta2: [0.999]
eps: 1.e-8
do_bias_correction: [false, true]
zero_init: true 

# Scheduler Configuration  
scheduler: ["warmup_cosine", null] 
warmup_steps: 0.1
lr_start: 1.e-6
lr_end: 1.e-6
cooldown_steps: null

# Logging Configuration
use_wandb: true
wandb_project: "bias_correction_experiments"
wandb_dir: "./wandb_logs"
wandb_api_key: ""
out_dir: "/fast/slaing/exp/vision"

# Checkpoint Configuration
save_intermediate_checkpoints: false
save_last_checkpoint: true
resume: false
resume_exp_name: null
over_write: false