# General Settings
deterministic: true
sampler_seed: 99
seed: 99
one_seeded: false

# Dataset Configuration
dataset: "cifar10"
data_dir: null  # Set to null for default paths
batch_size: [512, 1024]
num_workers: 4

# validation size
val_size: 0.2

# Model Configuration
model: "resnet9"

# Training Parameters
epochs: 150
optimizer: "adamw"
lr: [5.e-3, 7.e-3]  
weight_decay: [0.05]
beta1: [0.92]
beta2: 0.999
eps: 1.e-8
do_bias_correction: [false, true]  

# Scheduler Configuration  
scheduler: "warmup_cosine"
warmup_steps: 0.05
lr_start: 1.e-6
lr_end: 1.e-6
cooldown_steps: null

# Logging Configuration
use_wandb: true  # Set to false for debugging
wandb_project: "bias_correction_experiments"
wandb_dir: "./wandb_logs"
wandb_api_key: ""
out_dir: "/fast/slaing/exp/vision"

# Checkpoint Configuration
save_intermediate_checkpoints: false
save_last_checkpoint: true
resume: false
resume_exp_name: null
over_write: false