# General Settings
deterministic: true
sampler_seed: 99
seed: [600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614] 
one_seeded: true


# Dataset Configuration
cutmix: 0
cutmix_probability: 0
dataset: "cifar10"
data_dir: null  # Set to null for default paths
batch_size: [128]
num_workers: 4

# validation size
val_size: 0.0

# Model Configuration
model: "resnet9"

# Training Parameters
epochs: 175
optimizer: "adamw"
lr: [7.e-3]  
weight_decay: [0.05]
beta1: [0.91]
beta2: 0.999
eps: 1.e-8
do_bias_correction: [false, true] 
zero_init: [false, true]

dropout: null

# Scheduler Configuration  
scheduler: "warmup_cosine"
warmup_steps: 0.05
lr_start: 1.e-6
lr_end: 1.e-6
cooldown_steps: null

# Logging Configuration
use_wandb: true  # Set to false for debugging
wandb_project: "bias_correction_experiments"
wandb_dir: "./wandb_logs"
wandb_api_key: ""
out_dir: "/fast/slaing/exp/vision"

# Checkpoint Configuration
save_intermediate_checkpoints: false
save_last_checkpoint: true
resume: false
resume_exp_name: null
over_write: false