# General Settings
deterministic: true
sampler_seed: 2
seed: [99]
one_seeded: true  # Set to true for fully deterministic runs

# Dataset Configuration
dataset: "tiny_imagenet"
data_dir: null  # Set to null for default paths
batch_size: [128]  # Smaller batches for ViT which is parameter-heavy
num_workers: 4

# validation size
val_size: 0.1  # TinyImageNet already has a validation set

# Model Configuration
model: "ViT"  # Vision Transformer

# Training Parameters
epochs: 150 
optimizer: "adamw"
lr: [3.e-4] 
weight_decay: [0.1]  
beta1: 0.9  
beta2: 0.999 
eps: 1.e-8
do_bias_correction: [false, true]  
zero_init: [true, false]  

# Scheduler Configuration  
scheduler: "warmup_cosine"
warmup_steps: 0.1  # Longer warmup (10%) for ViT stability
lr_start: 1.e-6
lr_end: 1.e-6
cooldown_steps: null

# Logging Configuration
use_wandb: true
wandb_project: "bias_correction_experiments"
wandb_dir: "./wandb_logs"
wandb_api_key: ""
out_dir: "/fast/slaing/exp/vision"

# Checkpoint Configuration
save_intermediate_checkpoints: true  # Save checkpoints due to longer training
checkpoint_frequency: 20  # Save every 20 epochs
save_last_checkpoint: true
resume: false
resume_exp_name: null
over_write: false